### ISSUE TITLE
이 레포지토리를 각자의 계정으로 fork해보세요.

### ISSUE THREAD

**Issue by yhs0602** [SNU-SPLIT-17/SPLIT17QNA#4]
![image](https://user-images.githubusercontent.com/35697677/77072479-18c92a80-6a31-11ea-992f-5626beac4efb.png)

Fork 버튼을 누르면 어느 계정으로 포크할 것인지 물어볼 수도 있는데, 각자의 계정으로 fork를 해주세요. 그다음 그 주소를 여기에 댓글로 달아주세요.

Fork란 어떤 레포지토리(간단히 이야기하면 프로젝트 느낌입니다)를 복제하는 것을 의미합니다. 복제본에서 어떤 작업을 해도 원본 레포지토리에는 변경사항이 적용되지 않습니다.

**Comment by rhgusals97** [comment]
https://github.com/rhgusals97/SPLIT17QNA

**Comment by yhs0602** [comment]
잘 하셨습니다!
