### ISSUE TITLE
파일을 추가하셨다면 이것을 원본 (이 레포지토리)에 반영하기 위해 pull request를 만들어 봅시다.

### ISSUE THREAD

**Issue by yhs0602** [SNU-SPLIT-17/SPLIT17QNA#9]
튜티 본인의 레포지토리(forked from SNU-SPLIT-17/SPLIT17QNA라고 적혀 있음)에서 원본 레포지토리에 변경사항을 적용하기 위해서는 pull request라는 것을 이용해야 합니다.

![image](https://user-images.githubusercontent.com/35697677/77161515-35c33380-6aed-11ea-804d-39dbf39b4cdd.png)

이 버튼을 누르시면 
![image](https://user-images.githubusercontent.com/35697677/77161805-e7fafb00-6aed-11ea-9516-a5cd15c36e7d.png)

이런 화면으로 넘어갑니다. 이제 초록 버튼을 눌러 create pull request 화면으로 넘어갑니다. 
issue를 만드는 화면과 비슷하게 생겼습니다.

![image](https://user-images.githubusercontent.com/35697677/77161897-14167c00-6aee-11ea-8a98-6cc19d35d66d.png)

Create pull request를 누릅니다. 이제 원본 레포지토리에는 

![image](https://user-images.githubusercontent.com/35697677/77161942-2690b580-6aee-11ea-82df-94cf7914c702.png)

이렇게 새로운 pull request가 나타나는 것을 알 수 있습니다.

그러면 이 레포지토리에 충분한 권한을 갖고 있는 사람이 merge를 하거나 코멘트를 남기고, merge를 하게 되면(즉, pull request를 허가하면) 여러분의 변경내역이 원본에 반영되는 것입니다.

**Comment by rhgusals97** [comment]
![캡처](https://user-images.githubusercontent.com/62290218/77226332-daf80d80-6bba-11ea-9d5a-24e80842e9ee.JPG)

new pull request를 누르면 이렇게 떠서 다음단계로 넘어갈 수가 없어요ㅠㅠ

**Comment by yhs0602** [comment]
@rhgusals97 Pull request는 복사본에서 원본으로, 또는 원분에서 복사본으로 변경사항을 복제하는 것입니다. 현재 보여주신 사진을 보면 원본에서 원본으로 pull request를 만드시려는 것을 볼 수 있습니다. 현민님의 레포지토리에서 pull request를 만드시면 잘 될 거에요

**Comment by rhgusals97** [comment]
휴우 드디어 됐어요ㅠㅠㅠ흑 감사합니다....저때문에 늦어서죄송해요.......................ㅠ

**Comment by yhs0602** [comment]
잘 하셨습니다!
